AWSTemplateFormatVersion: 2010-09-09
Description: Web server config

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  KeyName:
    Description: Amazon EC2 KeyPair
    Type: String
  PublicSubnet1:
    Description: The subnet that the web server will be hosted in
    Type: String
  VPC:
    Description: VPC that contains the web server
    Type: String


Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-042e8287309f5df03 


Resources:
  WebServerEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        !Base64 |
        #!/bin/bash
        snap install docker
        sudo curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        chown $USER /var/run/docker.sock
        docker pull nfishel/filmclub
        docker tag nfishel/filmclub filmclub
        docker pull nginx
        docker pull redis
        git clone https://github.com/COSC481W-2021Winter/capstone-project-film-club.git
        cd capstone-project-film-club
        docker-compose up
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - !Ref AWS::Region
          - AMI
      Tags:
        - Key: Name
          Value: "Film Club Host"
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - Ref: "SecurityGroup"
          SubnetId:
            Ref: "PublicSubnet1"

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open Port 22 for ssh and port 1300 for the webserver
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 1300
          ToPort: 1300
          CidrIp: 0.0.0.0/0
