AWSTemplateFormatVersion: 2010-09-09
Description: Top stack to be used to deploy infrastructure for the Film club application

Parameters:
    #------------------------
    # Deployment Information
    #------------------------
    Environment:
      Type: String
      Description: Name of the environment to use in naming.
    CloudToolsBucket:
      Type: String
      Description: Name of the bucket this stack is being deployed from


Resources:

  VPC:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${CloudToolsBucket}/cloudformation/vpc.yml'
      Parameters:
        EnvironmentName: !Ref Environment

  ec2:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${CloudToolsBucket}/cloudformation/ec2.yml'
      Parameters:
        EnvironmentName: !Ref Environment
        KeyName: Capstone
        PublicSubnet1: !GetAtt VPC.Outputs.PublicSubnet1
        VPC: !GetAtt VPC.Outputs.VPC

